# Site settings
title: Dan's Portfolio
email: dan.scriptor@gmail.com
url: http://daniel.fyi
description: "Daniel's portfolio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-light: '#fff'
  primary-dark: '#4b4b4b'
  links: '#ff3680'

# Footer settings
footer: Footer

# Social link references
social:
  facebook: https://www.facebook.com/dan.scriptr/
  instagram: https://www.instagram.com/lifeonsmash/
  linkedin: https://www.linkedin.com/in/dan-scriptor/

# Static files
defaults:
  - scope:
      path: "img"
    values:
      image: true

# Build settings
markdown: kramdown
permalink: pretty
include: ['_pages']